#!/usr/bin/env python3
"""Generate bounded Unicode 17 tables from Unicode's official data files."""
from pathlib import Path
from urllib.request import urlopen
BASE = 'https://www.unicode.org/Public/17.0.0/ucd/'
files = {'gcb': 'auxiliary/GraphemeBreakProperty.txt', 'emoji': 'emoji/emoji-data.txt', 'width': 'EastAsianWidth.txt', 'incb': 'DerivedCoreProperties.txt'}
data = {key: urlopen(BASE + path, timeout=30).read().decode() for key, path in files.items()}
props = ['Other', 'CR', 'LF', 'Control', 'Extend', 'ZWJ', 'Regional_Indicator', 'Prepend', 'SpacingMark', 'L', 'V', 'T', 'LV', 'LVT']
def ranges(text, select):
    out=[]
    for line in text.splitlines():
        fields=[part.strip() for part in line.split('#')[0].split(';')]
        if len(fields)<2: continue
        value=select(fields)
        if value is None: continue
        bounds=fields[0].split('..'); out.append((int(bounds[0],16), int(bounds[-1],16),value))
    return sorted(out)
tables={
'gcb':ranges(data['gcb'],lambda f:props.index(f[1])),
'wide':ranges(data['width'],lambda f:1 if f[1] in ['W','F'] else None),
'emojiPresentation':ranges(data['emoji'],lambda f:1 if f[1]=='Emoji_Presentation' else None),
'pictographic':ranges(data['emoji'],lambda f:1 if f[1]=='Extended_Pictographic' else None),
'incb':ranges(data['incb'],lambda f: ['Consonant','Extend','Linker'].index(f[2])+1 if len(f)>2 and f[1]=='InCB' and f[2] in ['Consonant','Extend','Linker'] else None),
}
source='// Generated by scripts/generate-unicode.py. Unicode 17.0.0; see docs/Unicode-LICENSE.txt.\nimport Foundation\n\nenum UnicodeData {\n'
for name, rows in tables.items():
    source+=f'    static let {name}: [UInt32] = [\n'
    for a,b,value in rows:source+=f'        0x{a:X}, 0x{b:X}, {value},\n'
    source+='    ]\n'
source+='''    static func property(_ value: UInt32, in table: [UInt32]) -> UInt32 {
        var low = 0, high = table.count / 3
        while low < high {
            let mid = (low + high) / 2, index = mid * 3
            if value < table[index] { high = mid }
            else if value > table[index + 1] { low = mid + 1 }
            else { return table[index + 2] }
        }
        return 0
    }
}
'''
Path('Sources/TerminalCore/UnicodeData.swift').write_text(source)
Path('docs/Unicode-LICENSE.txt').write_bytes(urlopen('https://www.unicode.org/license.txt',timeout=30).read())
print({key: len(rows) for key,rows in tables.items()})
