// Authored Specter documentation. External documentation is reference material, never executable input.
export const guides = [
  {id:'overview', title:'Welcome to Specter', body:`
    <h1>A place for your work.</h1>
    <p>Specter is a native macOS terminal for Apple silicon. It runs your shell through a real POSIX pseudoterminal, renders with Metal, and gives you 130 original themes, native tabs, split panes, and profiles.</p>
    <div class="doc-note">Specter is a developer preview. Its terminal implementation is still growing. Read the compatibility guide and try your everyday tools before making it your primary terminal.</div>
    <h2>Start with a working shell</h2><p>Follow the <a href="docs.html?guide=install">build guide</a>, launch Specter, and type a command. By default it starts your login shell in your home directory. Your shell handles its own startup files.</p>
    <h2>Make the space yours</h2><ul><li>Press <kbd>⇧⌘T</kbd> to open the Theme Gallery.</li><li>Press <kbd>⌘T</kbd> for a tab, or <kbd>⌘D</kbd> for a split.</li><li>Press <kbd>⇧⌘P</kbd> to find any open session.</li><li>Open Settings with <kbd>⌘,</kbd> to configure profiles, type, and appearance.</li></ul>
    <h2>Read offline, too</h2><p>Choose Help → Specter Handbook in the app to open the included handbook in your browser. It is self-contained and needs no network connection to read.</p>
    <h2>Read what matters next</h2><p><a href="docs.html?guide=sessions">Organize sessions</a> · <a href="docs.html?guide=themes">Choose a theme</a> · <a href="docs.html?guide=compatibility">Check compatibility</a></p>`},
  {id:'install',title:'Download & install',body:`
    <h1>Up and running.</h1><p>Download the prebuilt developer preview for an Apple silicon Mac, or build from source with full Xcode, Swift 6, and Metal tools. macOS 14 is the deployment target; runtime testing covers an M3 Mac on macOS 26.3.1. There is no automatic updater.</p>
    <p><a href="https://github.com/shellcat-com/Specter/blob/main/docs/install.md">Download and installation guide on GitHub →</a> — Xcode setup, source downloads, and troubleshooting.</p>
    <h2>Download the app</h2><p><a href="https://github.com/shellcat-com/Specter/releases/tag/v0.1.0-preview.1">Get the preview ZIP and SHA-256 checksum on GitHub</a>. Extract it and move Specter.app into Applications. No Xcode is needed for this package.</p><div class="doc-note">This tester build is signed ad hoc, without Developer ID or Apple notarization. macOS may block it. Check the release and checksum, then follow <a href="https://support.apple.com/en-us/102445">Apple’s guidance for downloaded apps</a> if you decide to trust it. Do not disable system protections. A checksum verifies file integrity, not publisher identity. The source build below is another option.</div><p>Specter runs locally and needs no hosted Specter server or account. Internet tools use their own connections. To update a ZIP installation, save your work, quit Specter, and replace the app with a newer downloaded version. Keep your old copy if you want to roll back.</p><h2>Install from your terminal</h2><p>After setting up Xcode and Metal tools, run this in your current terminal:</p><pre><code>mkdir -p "$HOME/Developer" &amp;&amp; git clone https://github.com/shellcat-com/Specter.git "$HOME/Developer/Specter" &amp;&amp; "$HOME/Developer/Specter/scripts/install.sh"</code></pre>
    <p>This downloads source into <code>~/Developer/Specter</code>, builds locally, verifies the app signature, and installs in <code>~/Applications</code>. No administrator password is needed. If the source folder exists, run <code>./scripts/install.sh</code> from that checkout instead.</p><pre><code>open "$HOME/Applications/Specter.app"</code></pre>
    <h2>Update your copy</h2><p>Save your work and quit Specter. From another terminal, update an unmodified checkout and reinstall:</p><pre><code>cd ~/Developer/Specter
git pull --ff-only &amp;&amp; ./scripts/install.sh --replace</code></pre><p>The previous app is kept alongside the new one as a dated backup. To roll back, quit Specter, move the new app aside, and rename the backup to Specter.app. The installer never changes your shell configuration. Use <code>--destination /Applications</code> for a shared installation if that folder is writable by your user; use the same destination when updating.</p>
    <h2>Build without installing</h2><pre><code>scripts/build-app.sh
open .build/Specter.app</code></pre><p>The bundle includes the PTY helper, Metal resources, themes, terminfo, and offline handbook. Signing is local and ad hoc.</p>
    <h2>Building in a synced folder</h2><p>If signing reports a resource fork or Finder metadata error in an iCloud-synced checkout, package outside that folder:</p><pre><code>SPECTER_APP_OUTPUT=/private/tmp/Specter.app scripts/build-app.sh
open /private/tmp/Specter.app</code></pre><p>This changes only the output location. Signing remains local and ad hoc.</p>
    <h2>First launch</h2><p>A fresh terminal opens using your login shell. Check basic input with:</p><pre><code>printf 'Hello from Specter\\n'
printf '\\033[32mColor works\\033[0m\\n'
stty size</code></pre>
    <h2>Validate the source</h2><pre><code>scripts/check.sh
swift run SpecterBench
swift run SpecterBench --fuzz 600</code></pre><p>A passing build does not establish compatibility with every terminal application. The benchmark uses synthetic input and is not a comparison with other terminals.</p>`},
  {id:'sessions',title:'Tabs, splits & sessions',body:`
    <h1>Room for every moving part.</h1><p>Each terminal pane owns an independent PTY and shell. Use more than ten simultaneous sessions across tabs and windows without squeezing them all into one view.</p>
    <h2>Open and arrange</h2><table><tr><th>Action</th><th>Shortcut</th></tr><tr><td>New window</td><td>⌘N</td></tr><tr><td>New tab</td><td>⌘T</td></tr><tr><td>Split right</td><td>⌘D</td></tr><tr><td>Split below</td><td>⇧⌘D</td></tr><tr><td>Next pane</td><td>Control–Tab</td></tr><tr><td>Next / previous tab</td><td>⇧⌘] / ⇧⌘[</td></tr></table>
    <p>There are up to eight panes per tab. Splits use one shared orientation within that tab: splitting below changes the group to a vertical stack, while splitting right arranges the group side by side. Nested split trees are not implemented.</p>
    <h2>Find a session</h2><p>Open Window → Session Overview, or press <kbd>⇧⌘P</kbd>. Search by session number, profile, or window title, then select the session to focus it. The overview lists sessions when opened; reopen it to refresh the list.</p>
    <h2>A practical twelve-session workspace</h2><p>Create six tabs and split each once, or create twelve tabs. Give separate profiles to your server, tests, and scratch work. Use the overview to jump directly to a pane. Resource use grows with scrollback, terminal size, and the programs you run.</p>
    <h2>Close with care</h2><p><kbd>⌘W</kbd> closes the active pane, or its tab/window when it is the last pane. Closing stops the owned shell session. Save work in editors before closing. Programs deliberately detached from the terminal are outside Specter’s lifecycle ownership.</p>`},
  {id:'themes',title:'Themes & appearance',body:`
    <h1>Find your atmosphere.</h1><p>The 130-theme collection includes ten Specter originals and twenty color families with six treatments each: Midnight, Nocturne, Velvet, Dawn, Daylight, and Parchment. These are coordinated original variations, not imported community themes.</p>
    <h2>Browse and apply</h2><p>Open Specter → Theme Gallery, or press <kbd>⇧⌘T</kbd>. Search by name, choose Light or Dark, or save favorites with the star button. Selecting a preview immediately applies its colors to the selected profile and that profile’s open terminals. The header names the profile being edited.</p>
    <p>Use “Follow system appearance” to select Specter Night and Specter Day automatically as your Mac’s appearance changes. Individual light/dark pair customization is not implemented.</p>
    <h2>A companion for every terminal</h2><p>Choose from twelve original pixel companions: Wisp, Moth, Kettle, Mimic, Orbit, Moss, Bytebat, Cinder, Jelly, Origami, Imp, and Rover. Wisp is the default. Click Companions… above the shell or press <kbd>⇧⌘M</kbd> to open the native visual gallery. The options menu beside it offers quick design, motion, and animation controls.</p><p>Each terminal keeps its own companion, even when several terminals use the same profile. Open another window (<kbd>⌘N</kbd>), tab (<kbd>⌘T</kbd>), or split (<kbd>⌘D</kbd>) and choose a different character. In a split, the single strip follows the pane you focus. The gallery stays attached to the terminal that opened it. Session Overview (<kbd>⇧⌘P</kbd>) includes each terminal’s companion name.</p><p>Choose Idle, Busy, or Celebrate motion. These are decorative choices, not shell command status. Settings → Companion defaults for new terminals sets the initial choice for future terminals using that profile; existing terminals keep their own choices. If window restoration is enabled, each pane’s companion, motion, and animation setting are restored with fresh shells.</p><p>Animation runs at eight updates per second outside shell output. Pause preserves the current pose; inactive terminal windows and hidden views stop playback, and macOS Reduce Motion uses a still pose. Off removes the strip. Press <kbd>⇧⌘M</kbd> or choose Specter → Companions… to bring it back. Existing Specter, Comet, Sprout, and Pixel defaults migrate to Wisp, Cinder, Moss, and Rover, preserving Off and the animation setting.</p>
    <h2>Open with a look</h2><p>Shell → New Window with Theme and New Tab with Theme offer Basic (follow system), Dark, and Light choices across all 130 palettes and your custom themes. A theme choice creates a named profile with the default login shell, or reuses a matching named profile. Shell → New Window with Profile and New Tab with Profile launch your saved setups. The normal ⌘N and ⌘T shortcuts continue to use the profile selected in Settings.</p>
    <h2>Edit colors visually</h2><p>In the Theme Gallery, select a palette and choose Customize current. Change the name, background, text, cursor, selection, or any of sixteen ANSI colors with native color pickers or hexadecimal fields. The preview and default-text contrast update while you edit. Save &amp; Apply creates a new custom palette; Cancel discards the draft. Built-in palettes remain available. Custom colors are not automatically contrast-corrected: aim for at least 7:1 default text contrast and check ANSI colors separately.</p>
    <h2>Download, import, export</h2><p>Use the <a href="themes.html">web theme browser</a> to preview a palette and download its JSON. In Settings → Appearance, choose Import theme. Built-in themes already exist in the app; importing the identical file selects that theme. Use Customize current for a visual editor, or export a theme, give it a new unique ID and name, edit its colors, and import the file.</p>
    <p>Files are limited to 64 KiB. The schema requires version 1, an ID and name, background, foreground, cursor, selection, an isDark boolean, and exactly sixteen ANSI palette colors. Colors use six-digit <code>#RRGGBB</code> notation. A custom theme cannot replace a built-in ID with different colors.</p>
    <h2>Type and cursor</h2><p>Settings lets you choose an installed font, a size from 8 to 40 points, programming ligatures, and a block, bar, or underline cursor. Font coverage and ligatures depend on your chosen font.</p>
    <h2>Readable by default</h2><p>The included themes are checked for a minimum 7:1 contrast ratio between default text and background. ANSI colors, application-provided colors, and custom imports need separate contrast review. Reduced Motion disables the app’s cursor blink and website animation.</p>`},
  {id:'profiles',title:'Profiles & configuration',body:`
    <h1>A setup for each kind of work.</h1><p>Open Settings with <kbd>⌘,</kbd>. Add a profile with the plus button, name it, and configure its shell, initial directory, type, cursor, theme, and scrollback.</p>
    <h2>What applies when</h2><table><tr><th>Setting</th><th>Behavior</th></tr><tr><td>Theme, font, cursor</td><td>Updates matching open terminals.</td></tr><tr><td>Shell and working directory</td><td>Applies to new sessions. Existing processes keep running.</td></tr><tr><td>Scrollback</td><td>Used when a session is created; reopen the session to apply a new limit.</td></tr></table>
    <p>Leave shell and directory blank to use your login shell and home directory. Provide a path to a shell executable, not a command with arguments. Profile settings are stored locally in the app’s preferences.</p>
    <h2>Know the limits</h2><p>Scrollback is configurable from 1,000 to 100,000 rows per session. It is held in memory. Specter does not import Ghostty or iTerm configuration files, and does not edit your shell startup files. Keyboard shortcuts currently use the fixed native menu bindings.</p>`},
  {id:'shortcuts',title:'Keyboard & text',body:`
    <h1>Stay on the keyboard.</h1><table><tr><th>Action</th><th>Shortcut</th></tr><tr><td>Settings</td><td>⌘,</td></tr><tr><td>Theme Gallery</td><td>⇧⌘T</td></tr><tr><td>Session Overview</td><td>⇧⌘P</td></tr><tr><td>New window / tab</td><td>⌘N / ⌘T</td></tr><tr><td>Split right / below</td><td>⌘D / ⇧⌘D</td></tr><tr><td>Close pane</td><td>⌘W</td></tr><tr><td>Copy / paste / select all</td><td>⌘C / ⌘V / ⌘A</td></tr><tr><td>Find / find next</td><td>⌘F / ⌘G</td></tr><tr><td>Next pane</td><td>Control–Tab</td></tr><tr><td>Next / previous tab</td><td>⇧⌘] / ⇧⌘[</td></tr><tr><td>Quit</td><td>⌘Q</td></tr></table>
    <h2>Selection and mouse reporting</h2><p>Drag to select text. Hold Shift while dragging when an application has enabled mouse reporting. Find searches retained scrollback; use Previous and Next to navigate matches. Your shell’s history remains a separate feature managed by the shell.</p>
    <h2>Paste</h2><p>Pasting is an explicit user action. Multiline paste asks for confirmation. When the running application enables bracketed paste, Specter sends the corresponding bracketed input. Large input actions are bounded and rejected as a whole when the input queue cannot accept them.</p>
    <h2>Input methods</h2><p>Specter uses the native text input client for marked-text composition. Font fallback and Unicode cell handling are covered by synthetic tests. Full bidirectional layout and every input-method workflow have not been certified.</p>`},
  {id:'restoration',title:'Restore a workspace',body:`
    <h1>Return to a familiar layout.</h1><p>Enable “Reopen window layouts with fresh shells” in Settings. Restoration stores window geometry, tab grouping, split orientation, profile identifiers, and each pane’s companion choice, motion, and animation setting. It starts fresh shell processes on the next launch.</p>
    <div class="doc-note">Restoration does not resume running jobs or recover terminal output. It does not save commands, passwords, screen contents, or scrollback.</div>
    <p>The current restoration limit is twelve window/tab records with up to eight panes each. New shells start in the profile’s configured directory. Shell-reported working directories and process trees are not restored. Close and save important work deliberately before quitting.</p>
    <h2>Turn it off</h2><p>Disable restoration in Settings to start with a fresh window. Profile and theme preferences are retained separately.</p>`},
  {id:'compatibility',title:'Compatibility & roadmap',body:`
    <h1>Know what’s here.</h1><p>Specter implements its own terminal core. Ghostty’s documentation is a useful reference, but it is not a promise of Specter feature parity.</p>
    <table><tr><th>Area</th><th>Current Specter behavior</th></tr><tr><td>Platform</td><td>macOS 14+ target, Apple silicon. No Linux or Windows build.</td></tr><tr><td>Terminal basics</td><td>Cursor movement, erase, insert/delete, scroll regions, alternate screen, attributes, 16/256/RGB colors, application cursor keys and bracketed paste.</td></tr><tr><td>Text</td><td>UTF-8 decoding, Unicode grapheme handling, wide cells, reflow, Core Text fallback and optional ligatures. Full bidi layout is unsupported.</td></tr><tr><td>Native workspace</td><td>Windows, tabs, one-axis splits, session overview, profiles, search and selection.</td></tr><tr><td>Appearance</td><td>130 original themes, favorites, visual palette editing, safe JSON import/export, system light/dark selection, and twelve optional animated pixel companions.</td></tr><tr><td>Shell integration</td><td>Real login shells; no automatic injection of prompt hooks, command navigation, or SSH wrappers.</td></tr><tr><td>Graphics protocols</td><td>Kitty image protocol, sixel and image escape sequences are not implemented.</td></tr><tr><td>Extended protocols</td><td>Kitty keyboard, synchronized-output mode, OSC 133 prompt navigation, and automatic appearance reports are not implemented.</td></tr><tr><td>Customization</td><td>Native settings; no Ghostty config compatibility, arbitrary shaders, terminal wallpapers, global quick terminal, or AppleScript dictionary.</td></tr><tr><td>Distribution</td><td>Ad-hoc developer preview ZIP and source installer; no notarized release or auto-updater.</td></tr></table>
    <h2>Before making it your main terminal</h2><p>Exercise your editor, pager, multiplexer, SSH host, shell prompt, keyboard layout, and accessibility workflow. Report a minimal synthetic reproduction when something fails. A working prompt does not establish complete compatibility with an interactive application.</p>
    <h2>Next priorities</h2><ol><li>Broaden real application compatibility and accessibility evidence.</li><li>Improve split layouts and session lifecycle controls.</li><li>Add explicit, opt-in shell integration with documented boundaries.</li><li>Evaluate modern keyboard and rendering protocols with conformance tests.</li><li>Prepare signed distribution after release approval.</li></ol>`},
  {id:'ssh',title:'SSH & everyday use',body:`
    <h1>Your usual command line.</h1><p>Specter runs programs you start in the shell, including the system SSH client. It does not keep a host list, access credentials on its own, or automatically copy configuration to remote computers.</p>
    <h2>Remote terminal capabilities</h2><p>Specter bundles a conservative terminfo entry for local programs. A remote host may not know that entry. If the remote program reports an unknown terminal, a conservative one-session fallback is:</p><pre><code>TERM=xterm-256color ssh your-host</code></pre><p>Replace <code>your-host</code> with a host you normally use. This tells remote programs to use the xterm-256color capability description; it does not establish complete xterm compatibility. Do not add a persistent override until you have checked your own tools.</p>
    <h2>Using Specter as your main terminal</h2><p>Keep it in your Dock and open your day-to-day commands there. Specter does not silently change system defaults or your login shell. There is currently no built-in Finder “Open in Specter” service or default-terminal registration flow.</p>
    <h2>Move gradually</h2><p>Start with a familiar project. Test editing, full-screen redraw, resizing, copy/paste, international text, and long-running jobs. Keep your current terminal available until those workflows meet your needs.</p>`},
  {id:'privacy',title:'Privacy & security',body:`
    <h1>Your terminal stays yours.</h1><p>The terminal MVP has no accounts, cloud service, AI integration, email integration, telemetry, or automatic terminal-content logging. Programs you intentionally run can use the network according to their own behavior.</p>
    <h2>Untrusted output</h2><p>Escape sequences are parsed as terminal input, never executed as shell commands. OSC clipboard access is disabled. URLs are not opened automatically. Theme files contain palette data, not commands or scripts.</p>
    <h2>Explicit actions</h2><p>Copy and paste happen through user actions. Quick Look uses a file you select in an open panel. Secure Keyboard Entry can be enabled from the Specter menu. Background bell notifications are optional and use generic notification text.</p>
    <h2>Local settings</h2><p>Profiles and themes are stored in preferences. Optional restoration stores layout metadata. Your login shell may read its own configuration and maintain its own history; that behavior belongs to the shell.</p>
    <h2>This website</h2><p>The site serves its own assets and video from Vercel, with no added analytics or account system. Vercel handles ordinary web requests; downloads and source links go to GitHub. Theme files contain static palette JSON. Theme and documentation searches run in your browser; their text is not sent to a server.</p>`},
  {id:'troubleshooting',title:'Troubleshooting',body:`
    <h1>Get back to work.</h1><h2>The shell won’t start</h2><p>Check your profile’s shell and directory. Use an executable path such as <code>/bin/zsh</code>, not a command line. Confirm the directory exists. Build and launch the complete app bundle so the PTY helper is present. After correcting the profile, create a new session or use Restart shell.</p>
    <h2>Characters are missing or misaligned</h2><p>Try Menlo or another installed monospace font with the needed glyphs. Check your font size and disable ligatures to narrow the issue. Include synthetic text, chosen font, app revision, and expected cell layout in a bug report.</p>
    <h2>A fullscreen program draws incorrectly</h2><p>Try resizing once, then reduce the issue to a synthetic reproduction. Check the <a href="docs.html?guide=compatibility">unsupported protocols</a>. Do not assume a graphics or extended keyboard protocol is available.</p>
    <h2>A theme file is rejected</h2><p>Check the JSON schema, six-digit colors, sixteen palette entries, a unique ID, and the 64 KiB limit. A modified theme must use a new ID rather than a built-in ID. The web catalog’s unmodified files match the included themes.</p>
    <h2>Performance feels slow</h2><p>Reduce scrollback or the number of active panes while diagnosing. Shell → Export Performance Report saves local renderer counters through a file picker. These counters are diagnostic data, not proof of GPU timing. Use Instruments for actual memory or GPU measurements.</p>`},
  {id:'architecture',title:'Under the surface',body:`
    <h1>Native from the inside out.</h1><p>TerminalCore owns parser state, the grid, modes, and bounded scrollback. It is independent of UI and GPU frameworks. A serial session queue owns PTY reads and terminal mutation.</p>
    <h2>From bytes to pixels</h2><p>A small C launcher creates the PTY, starts the login shell, and owns its lifecycle. Swift receives the master descriptor. Immutable screen snapshots cross to AppKit, Core Text shapes text, and Metal draws atlas-backed cells. Rendering can coalesce snapshots; PTY bytes are not dropped to catch up.</p>
    <h2>Boundaries that matter</h2><p>Session input queues are bounded. Oversized input actions are rejected atomically. Terminal output is untrusted. UI effects require explicit handling, and clipboard or external navigation are not implicit escape-sequence effects.</p>
    <h2>Evidence over claims</h2><p>The repository includes parser and Unicode tests, PTY lifecycle checks, Metal snapshot tests, and synthetic benchmarks. Offscreen snapshots are distinct from screenshots of the running app. Local evidence records the toolchain, commands, actual results, and limits of testing.</p>`},
  {id:'credits',title:'Design & credits',body:`
    <h1>Thoughtful references. Original work.</h1><p>Specter’s website draws on the calm editorial spacing of <a href="https://cursor.com">Cursor</a> and the product focus and documentation organization of <a href="https://ghostty.org/docs">Ghostty</a>. Neither company endorses Specter. Their trademarks, testimonials, product screenshots, and proprietary typefaces are not used as Specter assets.</p>
    <p>The neutral studio backdrop, mark, orbital artwork, and theme collection are original Specter assets. An earlier generated dawn landscape is retained in the source archive but is no longer displayed. UI text uses system fonts.</p>
    <p>The engineering workflow adapts module boundaries, local evidence, isolated work, and clear writing from the reviewed <a href="https://github.com/michaelshimeles/skills">michaelshimeles/skills</a> repository. Greptile workflows and automatic uploads are excluded.</p>
    <p>Specter source is MIT licensed. Unicode data retains the Unicode license in the repository. See DESIGN.md and the research notes for the design system and reference review.</p>`}
];
